# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(.*/__generated__/.*.ts|eslint-plugin/out/.*|.*/pacts/.*|npins/.*|secret/.*)$
      - id: end-of-file-fixer
        exclude: ^(.*/__generated__/.*.ts|eslint-plugin/out/.*|.*/pacts/.*|npins/.*|secret/.*)$
      - id: check-yaml
        exclude: ^(packages/backend/aws-sam.template.yml)$
      - id: check-added-large-files
      - id: detect-private-key
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        name: check shell scripts
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-github-actions
        name: check github actions
      - id: check-github-workflows
        name: check github actions workflows

  # - repo: local
  # hooks:
  # - entry: /nix/store/d4b80pdbakylf5czc94ll3gwshmb0mmk-nix-linter-0.2.0.4/bin/nix-linter
  # files: "\\.nix$"
  # id: nix-linter
  # language: system
  # name: nix-linter
  # pass_filenames: true
  # stages:
  # - commit
  # types:
  # - file
  # - entry: /nix/store/m86nnc41fpsh8rbxmnlsyvk5g99hi1fp-nixpkgs-fmt-1.3.0/bin/nixpkgs-fmt
  # files: "\\.nix$"
  # id: nixpkgs-fmt
  # language: system
  # name: nixpkgs-fmt
  # pass_filenames: true
  # stages:
  # - commit
  # types:
  # - file
