packages:
  - "packages/*"

catalog:
  "@tsconfig/recommended": ^1.0.8
  fp-ts: ^2.16.9
  io-ts: ^2.2.21
  knip: ^5.36.3
  msw: ^2.6.0
  tsx: ^4.19.2
  typescript: ^5.6.3

catalogs:
  jest:
    "@swc/jest": ^0.2.37
    "@types/jest": ^29.5.14
    "@jest/globals": ^29.5.14
    jest: ^29.7.0
  typescript-node20:
    "@types/node": ^20.1.4
    "@tsconfig/node20": ^20.1.4
  typescript-node23:
    "@types/node": ^22.13.14
    "@tsconfig/node23": ^23.0.0
