name: checks

on:
  push:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  backend-compile:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-nodejs-pnpm
        name: Set up node.js with pnpm
        with:
          install-filter: backend
      - name: Run type checker
        working-directory: ./packages/backend
        run: pnpm tsc -b -v

  frontend-compile:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-nodejs-pnpm
        name: Set up node.js with pnpm
        with:
          install-filter: frontend
      - name: Run type checker
        working-directory: ./packages/frontend
        run: |
          pnpm run use-tsconfig dev
          pnpm tsc -b -v
  frontend-test-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: mcr.microsoft.com/playwright:v1.48.2-noble
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-nodejs-pnpm
        name: Set up node.js with pnpm
      - name: Run Playwright tests
        id: run-playwright-tests
        working-directory: ./packages/frontend
        run: pnpm playwright test --config=playwright.config.ts
        continue-on-error: true
        env:
          # Setting HOME fixes erros like: "Firefox is unable to launch if the $HOME folder isn't owned by the current user."
          # when using the Playwright Docker image.
          HOME: /root
          REACT_APP_API_BASE_URL: http://localhost
          REACT_APP_PORT: 8080
          PLAYWRIGHT_WEBSERVER_URL: http://localhost:8080
      - name: Upload Playwright report
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: ${{ ! cancelled() && steps.run-playwright-tests.conclusion != 'success' }}
        continue-on-error: true
        with:
          name: playwright-report
          path: ./playwright-report/
          retention-days: 1
      - name: Upload build
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        continue-on-error: true
        with:
          name: frontend
          path: ./packages/frontend/build
          retention-days: 1

  repo-test-unit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-nodejs-pnpm
        name: Set up node.js with pnpm
        with:
          install-recursive: true
      - name: Compile
        run: pnpm --recursive run compile
      - name: Run tests
        run: pnpm --recursive run test:unit

  repo-format-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-nodejs-pnpm
        name: Set up node.js with pnpm
        with:
          install-recursive: true
      - name: Run prettier
        id: run-prettier
        run: pnpm run format ${{ github.event_name == 'pull_request' && '--write' || '' }}
      - name: Run linter
        id: run-linter
        run: pnpm run lint ${{ github.event_name == 'pull_request' && '--fix' || '' }}
      - name: Commit and push fixed files
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        continue-on-error: true
        if: github.event_name == 'pull_request'
        with:
          add: .
          message: Fix eslint and prettier issues

  repo-knip:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - id: checkout-repo
        name: Checkout repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ./.github/actions/setup-nodejs-pnpm
        name: Set up node.js with pnpm
        with:
          install-recursive: true
      - name: Knip code
        run: pnpm run knip
